// The petition text, in one place, and the printable delivery packet built from it.
// Edit the petition here; the public page's copy in public/index.html should match.
const { esc } = require("./layout");

const PETITION = {
  title: "Petition to the Indiana General Assembly",
  subtitle: "For a state direct care staffing floor, protection of the caregivers who report, and accountability for nursing home Medicaid dollars",
  addressee: "To the Honorable Speaker and Members of the House of Representatives, and the Honorable President Pro Tempore and Members of the Senate, of the 125th General Assembly of the State of Indiana:",
  preamble: "The undersigned, residents of the State of Indiana, exercising the right secured by Article 1, Section 31 of the Constitution of the State of Indiana to instruct our representatives and to apply to the General Assembly for redress of grievances, respectfully represent:",
  whereas: [
    "Indiana law sets no minimum number of certified nurse aide hours or total direct care hours per resident day in comprehensive care facilities, requiring only one-half hour of licensed nurse time per resident day under 410 IAC 16.2-3.1-17, and Indiana is one of eighteen states with no direct care staffing minimum of any kind;",
    "an analysis of federal payroll-based staffing data published March 18, 2025 ranked Indiana fiftieth of the fifty states and the District of Columbia for total nurse staffing hours per resident after adjusting for resident acuity, and federal data for the first quarter of 2026 show that eighty-eight percent of Indiana nursing homes staffed below their residents' assessed needs;",
    "the federal minimum staffing standard finalized in May 2024 was repealed effective February 2, 2026, and Public Law 119-21 bars its enforcement until after September 30, 2034, so that no federal floor will exist for the remainder of this decade unless the State of Indiana sets one;",
    "county-owned hospitals hold the licenses to most Indiana nursing homes and, according to published investigative reporting drawing on records obtained through litigation, retained roughly $2.6 billion of $5.6 billion in supplemental Medicaid payments generated by those homes over approximately fifteen years, applying it to hospital construction, equipment, and operations rather than bedside care;",
    "a resident's rights are exercised through the frontline caregiver, and Indiana's at-will employment law, together with a thirty-day window to file a retaliation complaint, leaves that caregiver exposed to discipline, termination, and nurse aide registry referral for acts and omissions caused by conditions the facility created; and",
    "the safety of residents and the safety of the workers who care for them are one problem, and no resident right can be enforced by a worker who cannot act on it without losing their livelihood;",
  ],
  prayers: [
    "Introduce, hear in committee, and enact in the 2027 regular session the <b>Indiana Nursing Home Direct Care Staffing and Accountability Act</b>, adding IC 16-28-17, IC 16-28-18, IC 16-28-19, IC 16-28-20, and IC 16-22-15 to the Indiana Code and amending IC 16-28-5-4 and IC 16-28-9-3;",
    "Establish thereby a minimum direct care staffing standard of 3.00 total hours per resident day beginning July 1, 2027 and 3.48 hours beginning July 1, 2028, including 2.45 certified nurse aide hours and a registered nurse on site twenty-four hours a day, with acuity-based staffing above the minimum, annual unannounced acuity verification surveys, and public posting of staffing on every shift;",
    "Protect every direct care employee who reports an unsafe condition or refuses an unsafe assignment, through a rebuttable presumption of retaliation, a private right of action, and a systemic cause determination before any nurse aide registry finding, discipline, or termination for an act or omission caused by staffing below the standard, missing or inoperable equipment, an inaccurate assist level, or facility direction;",
    "Provide that penalties for staffing and retaliation violations exceed the cost of compliance, are not reduced upon correction, are not paid from Medicaid funds or charged to residents, and are deposited in a direct care restitution fund;",
    "Require county hospitals that hold nursing facility licenses to spend not less than eighty percent of the nursing facility supplemental Medicaid payments attributable to a facility on direct care at that facility, to file annual public facility-level accountings, and to repay diverted amounts; and",
    "Recognize the direct care workforce as a party to nursing home policy in Indiana, by consulting the Care Floor Coalition and the facility direct care staffing committees created by the Act in the development of rules, reimbursement, and oversight affecting long-term care, and by inviting direct care workers, residents, and families to testify at any hearing on the Act.",
  ],
  closing: "Respectfully submitted by the undersigned residents of Indiana, whose names appear on the attached paper signature sheets and on the Schedule of Signatures Collected Online (Exhibit B), each of whom has signed this petition once on the date shown.",
};

const PACKET_CSS = `.pk{max-width:8.5in;margin:0 auto;background:#fff;padding:0.6in;font-family:"Times New Roman",Times,serif;font-size:11.5pt;line-height:1.45;color:#000}.pk h1{text-align:center;font-size:15pt;letter-spacing:.05em;margin:0;text-transform:uppercase}.pk .sub{text-align:center;font-weight:700;font-size:11pt;margin:6px 0 18px}.pk .w{padding-left:1.6em;text-indent:-1.6em;margin:0 0 8px}.pk ol{padding-left:26px}.pk li{margin-bottom:6px}.pk table{font-size:9.5pt;margin-top:8px;width:100%;border-collapse:collapse}.pk th,.pk td{border:1px solid #000;padding:3px 5px;text-align:left}.pk h2{font-size:12.5pt;margin:22px 0 6px;page-break-after:avoid}.pb{page-break-before:always}.pk .cert{margin-top:18px;font-size:10.5pt}.pk .letter p{margin:0 0 10px}@media print{.pk{padding:0}}`;

function petitionHtml({ extraClosing = "" } = {}) {
  return `<h1>${esc(PETITION.title)}</h1><p class="sub">${esc(PETITION.subtitle)}</p><p>${esc(PETITION.addressee)}</p><p>${esc(PETITION.preamble)}</p>
  ${PETITION.whereas.map((w) => `<p class="w"><b>WHEREAS,</b> ${esc(w)}</p>`).join("")}
  <p><b>NOW, THEREFORE,</b> your petitioners respectfully pray that the General Assembly:</p><ol>${PETITION.prayers.map((p) => `<li>${p}</li>`).join("")}</ol>
  <p>${esc(PETITION.closing)}</p>${extraClosing}`;
}

function coverLetter({ legislator, coalition, contact, counts, today }) {
  const title = legislator.chamber === "House" ? "Representative" : "Senator";
  const chamber = legislator.chamber === "House" ? "Indiana House of Representatives" : "Indiana Senate";
  return `<div class="letter">
  <p><b>${esc(coalition)}</b><br>Indiana direct care workers, residents, and families<br>${esc(contact || "[contact]")}</p>
  <p>${esc(today)}</p>
  <p>The Honorable ${esc(legislator.name)}<br>${chamber}, District ${legislator.district}<br>200 West Washington Street<br>Indianapolis, Indiana 46204</p>
  <p><b>Re: Petition of your constituents for the Indiana Nursing Home Direct Care Staffing and Accountability Act</b></p>
  <p>Dear ${title} ${esc(legislator.name.split(" ").pop())}:</p>
  <p>Enclosed is a petition signed by residents of Indiana asking the General Assembly to enact, in the 2027 regular session, a state minimum direct care staffing standard for nursing homes, to protect the certified nurse aides and nurses who report unsafe conditions, and to require that the supplemental Medicaid payments Indiana nursing homes generate be spent on care in those homes. ${counts.district} of the signers listed in Exhibit B live in your district${counts.confirmed ? `, and ${counts.confirmed} of them have confirmed their signature by email` : ""}.</p>
  <p>Three facts explain why we are asking now. Indiana has never had a direct care staffing minimum; state law requires only one-half hour of licensed nurse time per resident per day and no certified nurse aide time at all. An analysis of federal payroll data published in March 2025 ranked Indiana fiftieth of the fifty states and the District of Columbia for staffing hours per resident, adjusted for how sick residents are. And the federal minimum staffing standard was repealed effective February 2, 2026, with Congress barring its enforcement until after September 30, 2034. For the next eight years, if Indiana does not set a floor, no one will.</p>
  <p>We ask three things of you. First, that you present this petition to your chamber so that it is entered in the record and referred to committee. Second, that you support, or agree to author or co-author, the draft Act. Third, that when the Act is heard, direct care workers, residents, and families from your district be given the opportunity to testify.</p>
  <p>The draft Act is written so that each of its four parts can stand alone. Its worker protection chapter carries essentially no fiscal note, and its second-phase staffing floor equals the repealed federal standard. It is a moderate bill. We would welcome twenty minutes with you or your staff, and we will make constituents available to meet in the district.</p>
  <p>Respectfully,</p><p><br><br>______________________________<br>${esc(coalition)}</p>
  <p style="font-size:10pt;font-style:italic">This letter names no facility and describes no individual case. It contains legal and policy information, not legal advice.</p></div>`;
}

// rows: signature records; group: "county" | "house" | "senate"; legislator: optional record for the cover letter
function packetHtml({ rows, group = "county", legislator = null, coalition, contact, paperNote = "" }) {
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const key = group === "house" ? (r) => (r.house_district ? `House District ${r.house_district}` : "District not yet determined") : group === "senate" ? (r) => (r.senate_district ? `Senate District ${r.senate_district}` : "District not yet determined") : (r) => `${r.county} County`;
  const groups = {};
  rows.forEach((r) => { const k = key(r); (groups[k] = groups[k] || []).push(r); });
  const confirmed = rows.filter((r) => r.confirmed_at).length;
  const letter = legislator ? coverLetter({ legislator, coalition, contact, counts: { district: rows.length, confirmed }, today }) + '<div class="pb"></div>' : "";
  const sortKeys = Object.keys(groups).sort((a, b) => { const na = parseInt(a.replace(/\D/g, ""), 10), nb = parseInt(b.replace(/\D/g, ""), 10); return group === "county" || isNaN(na) || isNaN(nb) ? a.localeCompare(b) : na - nb; });
  return `<style>${PACKET_CSS}</style><div class="pk">${letter}${petitionHtml({ extraClosing: `
    <p style="margin-top:14px">Presented to the [House of Representatives / Senate] by the Honorable ______________________________, District ____, on ______________, 20____, for referral to the Committee on ______________________________.</p>
    <p>Submitted on behalf of the petitioners by ${esc(coalition)}. Signatures attached: ${rows.length} online (Exhibit B)${confirmed ? `, ${confirmed} confirmed by email` : ""}${paperNote ? `; ${esc(paperNote)}` : "; plus ______ on paper sheets"}.</p>` })}
    <h2 class="pb">EXHIBIT B · SCHEDULE OF SIGNATURES COLLECTED ONLINE</h2>
    <p>The signatures listed below were submitted through the coalition's petition website, on which each signer entered their printed name, residence address, county, and the date, and affirmed that they are a resident of Indiana, that they signed once, and that the information given is true. Each record was received by the coalition by email at the time of signing and is reproduced here without alteration. Where a signer gave an email address and confirmed the signature by opening a link sent to that address, the entry is marked "confirmed". Legislative districts were determined from the residence address using the United States Census Bureau geocoder. Residence addresses are provided to the presenting member and the committee and are not otherwise published. Prepared ${esc(today)}.</p>
    ${sortKeys.map((k) => `<h2>${esc(k)} (${groups[k].length})</h2><table><tr><th style="width:24px">#</th><th>Printed name</th><th>Residence address</th><th>County</th><th>HD / SD</th><th>Signer</th><th style="width:74px">Date</th><th>Conf.</th></tr>${groups[k].map((r, i) => `<tr><td>${i + 1}</td><td>${esc(r.name)}</td><td>${esc(r.street)}, ${esc(r.city)}, IN ${esc(r.zip)}</td><td>${esc(r.county)}</td><td>${r.house_district || "–"} / ${r.senate_district || "–"}</td><td>${esc(r.role.replace(/ in Indiana long-term care$/, "").replace(/ \(.*\)$/, ""))}</td><td>${esc(String(r.created_at).slice(0, 10))}</td><td>${r.confirmed_at ? "✓" : ""}</td></tr>`).join("")}</table>`).join("") || "<p>No online signatures in this selection.</p>"}
    <p class="cert">Certification: I certify that the entries above are a true transcription of signature records received by ${esc(coalition)} through its petition website, that duplicate submissions were removed, and that the original records are retained and available to the presenting member on request.</p>
    <p class="cert">Signature: ______________________________ &nbsp;&nbsp; Printed name: ______________________________ &nbsp;&nbsp; Date: ______________</p>
  </div>`;
}

module.exports = { PETITION, petitionHtml, packetHtml, coverLetter };
